server:
  port: 8484
  ssl:
    key-alias: 1
    key-store: src/main/resources/server_cert.p12
    key-store-password: password
    key-password: password
    key-store-type: pkcs12
    enabled: true


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UserInfoDataBase
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
